version: "1.0"

services:
  app:    
      container_name: app
      build:      
        context: .
        dockerfile: dockerfile   
      ports:
        - "7090:80"
  seq:
      image: datalust/seq:latest
      container_name: seq
      ports:
      - '5341:80'
      environment:
      - ACCEPT_EULA=Y
      networks:
      - gateway-network

networks:
  gateway-network:
      name: gateway-network